### ISSUE TITLE
Occasional 500 due to failure not found

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/test-observability#73]
[This ably-cocoa CI run](https://github.com/ably/ably-cocoa/actions/runs/4865353931/jobs/8675547511?pr=1708) failed due to a 500 response when trying to upload to observability server. Logs from Heroku:

```
2023-05-02T22:46:28.600860+00:00 app[web.1]: [Nest] 20  - 05/02/2023, 10:46:25 PM   ERROR [ExceptionsHandler] No failure found with testClassName AuthTests and testCaseName test__010__Token__token_auth__should_work_over_HTTP()
2023-05-02T22:46:28.600968+00:00 app[web.1]: Error: No failure found with testClassName AuthTests and testCaseName test__010__Token__token_auth__should_work_over_HTTP()
2023-05-02T22:46:28.600977+00:00 app[web.1]: at UploadsService.populateCrashReportsForFailures (/app/dist/src/uploads/uploads.service.js:85:23)
2023-05-02T22:46:28.600979+00:00 app[web.1]: at UploadsService.create (/app/dist/src/uploads/uploads.service.js:49:24)
2023-05-02T22:46:28.600979+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-02T22:46:28.600979+00:00 app[web.1]: at async PostUploadsController.create (/app/dist/src/uploads/postUploads.controller.js:126:24)
2023-05-02T22:46:28.600979+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
2023-05-02T22:46:28.600980+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by lawrence-forooghian** [comment]
Another example [here](https://github.com/ably/ably-cocoa/actions/runs/4865353935/jobs/8680136881):

```
2023-05-03T06:16:01.617156+00:00 app[web.1]: [Nest] 20  - 05/03/2023, 6:16:01 AM   ERROR [ExceptionsHandler] No failure found with testClassName AuthTests and testCaseName test__028__Token__authentication_method__local_token_validity_check__should_be_done_if_queryTime_is_true_and_local_time_is_in_sync_with_server()
2023-05-03T06:16:01.617212+00:00 app[web.1]: Error: No failure found with testClassName AuthTests and testCaseName test__028__Token__authentication_method__local_token_validity_check__should_be_done_if_queryTime_is_true_and_local_time_is_in_sync_with_server()
2023-05-03T06:16:01.617213+00:00 app[web.1]: at UploadsService.populateCrashReportsForFailures (/app/dist/src/uploads/uploads.service.js:85:23)
2023-05-03T06:16:01.617213+00:00 app[web.1]: at UploadsService.create (/app/dist/src/uploads/uploads.service.js:49:24)
2023-05-03T06:16:01.617214+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-03T06:16:01.617214+00:00 app[web.1]: at async PostUploadsController.create (/app/dist/src/uploads/postUploads.controller.js:126:24)
2023-05-03T06:16:01.617214+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
2023-05-03T06:16:01.617214+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by lawrence-forooghian** [comment]
I believe that this is probably an issue with ably-cocoa — that is, that for some reason it's uploading crash reports with no corresponding test failures in the JUnit report. Unfortunately, ably-cocoa’s `1279-run-tests-in-loop` branch was not uploading the `.xcresult` test bundles upon upload failure, meaning I didn't have enough information to debug this. I have addressed this now, so next time this happens we should be better equipped to investigate.

**Comment by lawrence-forooghian** [comment]
This one seems so rare that I don't think it's worth keeping an issue open for — if it happens again, I'll raise a new issue, this time in ably-cocoa.
